services:
  app:
    image: almuko/uibirzhasi-app:latest
    container_name: uibirzhasi_app
    working_dir: /var/www
    restart: always
    env_file:
      - .env
    volumes:
      - appdata:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: uibirzhasi_web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - appdata:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: uibirzhasi_db
    restart: always
    environment:
      MYSQL_DATABASE: uibirzhasi
      MYSQL_USER: root
      MYSQL_PASSWORD: Zxcvbnm123
      MYSQL_ROOT_PASSWORD: Zxcvbnm123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - uibirzhasi_mysql_data:/var/lib/mysql

volumes:
  uibirzhasi_mysql_data:
  appdata:
